### PR TITLE
merge macosDir & linuxDir into unixDir

### PR DESCRIPTION
**Pull request by vastpeng**
In some condition, we work on macOS and linux together, maybe it's nice to put storage path together in unix system.

sorry for my poor English.

relate issue: #14

### CODE REVIEW

**Comment by sqshq** [comment]
Hi @vastpeng,
Did not understand the statement - what do you mean on macOS and Linux together? Maybe I am missing something, could please describe in more detail?

**Comment by vastpeng** [comment]
Sometimes we work on both macOS and Linux, and syncing dotfiles. So we can set the storage path in the same directory when using unix-like system.

**Comment by Asherslab** [comment]
i mean, on OSX you could just symlink the file if you're syncing them?

**Comment by sqshq** [comment]
Agree. Also I would prefer usual OS-specific directories for application files. Let's keep it as is for now

**Pull request closed without merging**
