### PR TITLE
Added Chocolatey install instructions for Windows.

### PR DESCRIPTION
**Pull request by digitalcoyote**
Updating ReadMe as documentation for #75

### CODE REVIEW

**Comment by digitalcoyote** [comment]
If you would prefer to hold off on this until the package is approved (makes it publicly visible), I'll post an update here once it  through moderation.

**Comment by sqshq** [comment]
Hi @digitalcoyote, thank you for the contribution! Yes, since it can take a couple of weeks, let's wait until it is approved to not confused people in the meantime

**Comment by digitalcoyote** [comment]
[Sampler](https://chocolatey.org/packages/sampler) has been approved quicker than usual.

**Comment by sqshq** [comment]
Great news! Thank you, @digitalcoyote

**Pull request merged**
