### PR TITLE
Fix user home directory for linux to work on both ubuntu and centos, without loosing cross-compilation support

### PR DESCRIPTION
**Pull request by sqshq**

### CODE REVIEW

**Comment by Asherslab** [comment]
That's great! thanks mate

**Comment by sqshq** [comment]
@Asherslab thank you for reporting this! Did you check it on Centos7 btw? Works good?

**Comment by Asherslab** [comment]
@sqshq sadly, i get this still:
```
go: finding github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
# github.com/sqshq/sampler/metadata
metadata/storage.go:26:14: undefined: os.UserHomeDir
```

**Comment by sqshq** [comment]
@Asherslab my bad, we need the same way to get homedir for macOS too
If it is not too much trouble, could please give it a try one more time? :)

**Comment by Asherslab** [comment]
Sure thing. i can also test on macOS too (if you can't yourself)

**Comment by sqshq** [comment]
MacOS looks good, I've tested it on my side

**Comment by Asherslab** [comment]
Works like a charm!

**Comment by sqshq** [comment]
Awesome! Thank you for your help!

**Pull request merged**
